### ISSUE TITLE
Python setup.py install deprecation

### ISSUE THREAD

**Issue by bkmgit** [hpc-carpentry/amdahl#12]
This will be deprecated in Python 3.12 (https://docs.python.org/3/install/index.html). 
Get the following warning:

```python
SetuptoolsDeprecationWarning: setup.py install is deprecated.
Use build and pip and other standards-based tools.
```

pyproject.toml with hatchling seems to be the recommended approach:
https://packaging.python.org/en/latest/tutorials/packaging-projects/
https://scikit-hep.org/developer/pep621
https://discuss.python.org/t/removing-setup-cfg-and-setup-py-from-the-packaging-tutorial/16096/102?page=2

**Comment by afuetterer** [comment]
I would like to pick up this issue. If I submit a PR, will there be anyone at HPC Carpentry to review?

**Comment by reid-a** [comment]
Yes! The project is actively maintained.

**Comment by afuetterer** [comment]
Do you want to have some kind of safety net? Checking that it works after the switch to pyproject.toml as it did before? There are no unit tests and no CI present.
I cannot run without an mpi library.

I could offer this gha setup:

```yaml
name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup openmpi
        uses: mpi4py/setup-mpi@v1
        with:
          mpi: openmpi
      - run: mpirun --version
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - run: python -m pip install --upgrade pip
      - run: python -m pip install .
      - run: python -m pip list
      - run: mpirun -np 2 amdahl
```

This runs succesfully in my fork. It is not a unit test, but it can act as some kind of safety net. What do you think?
